package com.aifactory.cloud;

import android.app.Activity;
import android.os.Bundle;
import android.webkit.WebView;

public class MainActivity extends Activity {
    public void onCreate(Bundle b) {
        super.onCreate(b);

        WebView web = new WebView(this);
        web.getSettings().setJavaScriptEnabled(true);

        String html =
        "<html><body style='font-family:Arial;padding:30px'>" +
        "<h1>AI Factory APK Works</h1>" +
        "<p>This APK was generated by the AI Factory.</p>" +
        "<button onclick=\"document.getElementById('r').innerHTML='Button works'\">Test Button</button>" +
        "<p id='r'></p>" +
        "</body></html>";

        web.loadDataWithBaseURL(null, html, "text/html", "UTF-8", null);
        setContentView(web);
    }
}
